// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: protobuff/book.proto

package protobuff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookName string `protobuf:"bytes,1,opt,name=BookName,proto3" json:"BookName,omitempty"`
}

func (x *BookName) Reset() {
	*x = BookName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookName) ProtoMessage() {}

func (x *BookName) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookName.ProtoReflect.Descriptor instead.
func (*BookName) Descriptor() ([]byte, []int) {
	return file_protobuff_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookName) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

type SearchAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authors string `protobuf:"bytes,1,opt,name=Authors,proto3" json:"Authors,omitempty"`
}

func (x *SearchAuthorRequest) Reset() {
	*x = SearchAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAuthorRequest) ProtoMessage() {}

func (x *SearchAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAuthorRequest.ProtoReflect.Descriptor instead.
func (*SearchAuthorRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_book_proto_rawDescGZIP(), []int{1}
}

func (x *SearchAuthorRequest) GetAuthors() string {
	if x != nil {
		return x.Authors
	}
	return ""
}

type Books struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book []*BookInfo `protobuf:"bytes,1,rep,name=Book,proto3" json:"Book,omitempty"`
}

func (x *Books) Reset() {
	*x = Books{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_book_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Books) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Books) ProtoMessage() {}

func (x *Books) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_book_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Books.ProtoReflect.Descriptor instead.
func (*Books) Descriptor() ([]byte, []int) {
	return file_protobuff_book_proto_rawDescGZIP(), []int{2}
}

func (x *Books) GetBook() []*BookInfo {
	if x != nil {
		return x.Book
	}
	return nil
}

type BookInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Authors []string `protobuf:"bytes,2,rep,name=Authors,proto3" json:"Authors,omitempty"`
}

func (x *BookInfo) Reset() {
	*x = BookInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuff_book_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInfo) ProtoMessage() {}

func (x *BookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_book_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInfo.ProtoReflect.Descriptor instead.
func (*BookInfo) Descriptor() ([]byte, []int) {
	return file_protobuff_book_proto_rawDescGZIP(), []int{3}
}

func (x *BookInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookInfo) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

var File_protobuff_book_proto protoreflect.FileDescriptor

var file_protobuff_book_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x62, 0x6f, 0x6f, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2f,
	0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x22,
	0x26, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x38, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x73, 0x32, 0x5c, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x1f, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x09,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x06, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x12, 0x2c, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x12, 0x14, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42,
	0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuff_book_proto_rawDescOnce sync.Once
	file_protobuff_book_proto_rawDescData = file_protobuff_book_proto_rawDesc
)

func file_protobuff_book_proto_rawDescGZIP() []byte {
	file_protobuff_book_proto_rawDescOnce.Do(func() {
		file_protobuff_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuff_book_proto_rawDescData)
	})
	return file_protobuff_book_proto_rawDescData
}

var file_protobuff_book_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuff_book_proto_goTypes = []interface{}{
	(*BookName)(nil),            // 0: BookName
	(*SearchAuthorRequest)(nil), // 1: SearchAuthorRequest
	(*Books)(nil),               // 2: Books
	(*BookInfo)(nil),            // 3: BookInfo
}
var file_protobuff_book_proto_depIdxs = []int32{
	3, // 0: Books.Book:type_name -> BookInfo
	0, // 1: BookService.SearchBook:input_type -> BookName
	1, // 2: BookService.SearchAuthor:input_type -> SearchAuthorRequest
	2, // 3: BookService.SearchBook:output_type -> Books
	2, // 4: BookService.SearchAuthor:output_type -> Books
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuff_book_proto_init() }
func file_protobuff_book_proto_init() {
	if File_protobuff_book_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuff_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_book_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Books); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuff_book_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuff_book_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_book_proto_goTypes,
		DependencyIndexes: file_protobuff_book_proto_depIdxs,
		MessageInfos:      file_protobuff_book_proto_msgTypes,
	}.Build()
	File_protobuff_book_proto = out.File
	file_protobuff_book_proto_rawDesc = nil
	file_protobuff_book_proto_goTypes = nil
	file_protobuff_book_proto_depIdxs = nil
}
